### ISSUE TITLE
Edit request string encoding error

### ISSUE THREAD

**Issue by venkatesh-sivaraman** [venkatesh-sivaraman/fireroad-server#11]
Got this in output for `update_db.py`:
```
Traceback (most recent call last):
 File "/opt/fireroad/fireroad/update_db.py", line 267, in <module>
   message += check_for_edits()
 File "/opt/fireroad/fireroad/update_db.py", line 190, in check_for_edits
   message += str(req) + "\n"
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 54: ordinal not in range(128)
```

**Comment by venkatesh-sivaraman** [comment]
Fixed with [most recent commit](https://github.com/venkatesh-sivaraman/fireroad-server/commit/9a75d3aff168015fe7e27f3d8abefb03c3e048e7)
