### ISSUE TITLE
Requirements with manual progress crash

### ISSUE THREAD

**Issue by venkatesh-sivaraman** [venkatesh-sivaraman/fireroad-server#23]
Looks to be due to #22. Representative stack trace:

```
[Tue Jan 12 22:45:34.082566 2021] [:error] [pid 24728] Internal Server Error: /requirements/progress/girs/
[Tue Jan 12 22:45:34.082576 2021] [:error] [pid 24728] Traceback (most recent call last):
[Tue Jan 12 22:45:34.082581 2021] [:error] [pid 24728]   File "/opt/fireroad/env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
[Tue Jan 12 22:45:34.082585 2021] [:error] [pid 24728]     response = get_response(request)
[Tue Jan 12 22:45:34.082590 2021] [:error] [pid 24728]   File "/opt/fireroad/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
[Tue Jan 12 22:45:34.082595 2021] [:error] [pid 24728]     response = self._get_response(request)
[Tue Jan 12 22:45:34.082599 2021] [:error] [pid 24728]   File "/opt/fireroad/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
[Tue Jan 12 22:45:34.082604 2021] [:error] [pid 24728]     response = self.process_exception_by_middleware(e, request)
[Tue Jan 12 22:45:34.082609 2021] [:error] [pid 24728]   File "/opt/fireroad/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
[Tue Jan 12 22:45:34.082613 2021] [:error] [pid 24728]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Jan 12 22:45:34.082618 2021] [:error] [pid 24728]   File "/opt/fireroad/env/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
[Tue Jan 12 22:45:34.082623 2021] [:error] [pid 24728]     return view_func(*args, **kwargs)
[Tue Jan 12 22:45:34.082627 2021] [:error] [pid 24728]   File "/opt/fireroad/fireroad/requirements/views.py", line 126, in road_progress
[Tue Jan 12 22:45:34.082636 2021] [:error] [pid 24728]     return road_progress_post(request, list_id)
[Tue Jan 12 22:45:34.082640 2021] [:error] [pid 24728]   File "/opt/fireroad/fireroad/requirements/views.py", line 105, in road_progress_post
[Tue Jan 12 22:45:34.082645 2021] [:error] [pid 24728]     result = compute_progress(request, list_id, read_subjects(contents), progress_overrides, progress_assertions)
[Tue Jan 12 22:45:34.082650 2021] [:error] [pid 24728]   File "/opt/fireroad/fireroad/requirements/views.py", line 60, in compute_progress
[Tue Jan 12 22:45:34.082655 2021] [:error] [pid 24728]     prog.compute(course_objs, progress_overrides, progress_assertions)
[Tue Jan 12 22:45:34.082659 2021] [:error] [pid 24728]   File "/opt/fireroad/fireroad/requirements/progress.py", line 381, in compute
[Tue Jan 12 22:45:34.082664 2021] [:error] [pid 24728]     req_progress.compute(courses, progress_overrides, progress_assertions)
[Tue Jan 12 22:45:34.082668 2021] [:error] [pid 24728]   File "/opt/fireroad/fireroad/requirements/progress.py", line 403, in compute
[Tue Jan 12 22:45:34.082673 2021] [:error] [pid 24728]     satisfied_by_category = [sat for prog, sat in sorted(zip(open_children, satisfied_by_category), key = lambda z: z[0].raw_fraction_fulfilled, reverse = True)]
[Tue Jan 12 22:45:34.082678 2021] [:error] [pid 24728]   File "/opt/fireroad/fireroad/requirements/progress.py", line 403, in <lambda>
[Tue Jan 12 22:45:34.082683 2021] [:error] [pid 24728]     satisfied_by_category = [sat for prog, sat in sorted(zip(open_children, satisfied_by_category), key = lambda z: z[0].raw_fraction_fulfilled, reverse = True)]
[Tue Jan 12 22:45:34.082688 2021] [:error] [pid 24728] AttributeError: 'RequirementsProgress' object has no attribute 'raw_fraction_fulfilled'
```

**Comment by venkatesh-sivaraman** [comment]
Closed via #24
